# Molecule managed
# https://github.com/hashicorp/docker-vault/blob/master/0.X/Dockerfile

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN mkdir -p /usr/share/man/man1

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get upgrade -y && apt-get install -y python sudo bash ca-certificates gzip tar unzip curl wget git gnupg2 apt-transport-https python-apt libcap2-bin iproute2 && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python3 sudo python3-devel python3-dnf bash shadow-utils gzip tar unzip curl wget git gnupg2 python3-libselinux initscripts hostname iproute && alternatives --set python /usr/bin/python3 && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash shadow-utils gzip unzip tar curl wget git gnupg2 initscripts hostname shadow-utils && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper update -y && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; fi

ENTRYPOINT []

# https://github.com/gdraheim/docker-systemctl-replacement
RUN cd /tmp \
  && curl -sLO https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py \
  && yes | cp -f systemctl.py /usr/bin/systemctl \
  && chmod a+x /usr/bin/systemctl \
  && mkdir -p /run/systemd/system/ \
  && rm -rf /sbin/initctl

# https://github.com/Yelp/dumb-init
RUN DUMBINIT_VERSION=1.2.2 \
  && wget -q -O /usr/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v${DUMBINIT_VERSION}/dumb-init_${DUMBINIT_VERSION}_amd64 \
  && chmod +x /usr/bin/dumb-init

# https://github.com/tianon/gosu
# https://gist.github.com/rafaeltuelho/6b29827a9337f06160a9
# https://cinhtau.net/2017/06/19/install-gosu-for-docker/
RUN GOSU_VERSION=1.11 \
  && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
  && curl -o /usr/bin/gosu -sSL "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64" \
  && curl -o /usr/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64.asc" \
  && gpg --batch --verify /usr/bin/gosu.asc /usr/bin/gosu \
  && rm /usr/bin/gosu.asc \
  && rm -rf /root/.gnupg/ \
  && chmod +x /usr/bin/gosu \
  && gosu nobody true

# create vault user and group
RUN groupadd vault \
  && useradd -g vault vault
